### ISSUE TITLE
自動再起動の導入

### ISSUE THREAD

**Issue by mikamix** [veeple/atenza#15]

**Comment by mikamix** [comment]
supervisordでやる

**Comment by mikamix** [comment]
できれば電源ONで起動

**Comment by KeixVpl** [comment]
標準出力とエラー出力わける。
斜め読みしました。redirect_std_errorがtrueになってるので、通常ログとエラーログが混ざりますが、それは大丈夫ですかね? この辺は決めの問題でもありますが、ごっちゃになると読みづらかったりするぐらいです。

[5:40]  
まあやってみて分けたかったら分けるでもいいかと。

[5:41]  
分けたい場合はstderror_logfileを指定すればstdoutとstderrorが分かれます。

[5:42]  
ただ、そもそもparticlesとsensingdはたぶんエラーをstdoutに出してる状態だと思うので、どこまでやるかは微妙ですね。

[5:43]  
もしやるならpythonは http://april.fool.jp/blogs/2014/07/%E3%83%A1%E3%83%A2-python%E3%81%A7%E6%A8%99%E6%BA%96%E3%82%A8%E3%83%A9%E3%83%BC%E5%87%BA%E5%8A%9B%E3%81%AB%E8%A1%A8%E7%A4%BA%E3%81%99%E3%82%8B%E3%81%AB%E3%81%AF/

[5:43]  
みたいな感じでエラーだけstderrorに出してあげればって感じです。

[5:45]  
ちょっといいドキュメント見つからなかったですが、Linuxの標準出力(stdout)と標準エラー出力(stderror)については http://www.creatology.jp/unix/outin.html この辺を見るとわかりやすいかもです。
プログラム側で標準出力とエラー出力を分けるのと、supervisor側でそれを別のファイルに書くのはそれぞれ別のこと
